theme: jekyll-theme-minimal
title: Eric Schnelker Home Page
description: Bookmark this to keep an eye on my project updates!
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - SchnelkerArchDocumentation.md
