theme: jekyll-theme-minimal
title: Eric Schnelker Home Page
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - SCHNELKER_ARCH_DOCUMENTATION.md
  - SCHNELKER_DOCKER_DOCUMENTATION.md
permalink: /SCHNELKER_ARCH_DOCUMENTATION.md
